algo: tppo
single: 'amq'
envparameters:
  action_continuous: true
  action_space: 1
  n_player: 1
  obs_continuous: true
  obs_space: 9
  action_interval: 1
  action_max: 20.0  #WASTED
  action_max_0: 1.0
  action_max_1: 0.3
  mlp: false
  boots_num: 2
scenario: iff
hyperparameters:
  mode: 'separate_Q'
  sigma_type: 'share'  #share or variable
  n_ensemble: 2
  load_pretrained: false
  load_actor: true
  load_critic: true
  cls: false
  batch_size: 256
  offline_batch_size: 1600
  buffer_capacity: 10000
  c_lr: 0.0003 #0.005
  a_lr: 0.0001
  q_lr: 0.001 #0.0005
  context_len: 40
  n_layer: 2
  n_head: 2  #2
  n_embed: 32  #32
  gamma: 0.99
  ppo_epoch: 8
  ppo_clip: 0.2
  ppo_entropy: 0.01
  grad_norm_clip: 0.5
  gae_lambda: 0.95
  St: 0.2
  AD: 0.1
  theta: 70
  Phi: 190
  is_double_q: false #IQL
  sa_type: 'separate' #'separate' or 'concat'
  omega: 0.8
  target_update_freq: 4
  tau: 0.005
  # actor_path: '/home/iff/drlenv/src/iffenv/src/off2on_models/actor_1_6499.pth'
  # actor_path: '/home/iff/drlenv/src/iffenv/src/pretrained_models/actor_10113_09_09_17_43.pth'
  # critic_path: '/home/iff/drlenv/src/iffenv/src/off2on_models/V_new_best_118_0.2348.pth'
  # critic_path: '/home/iff/drlenv/src/iffenv/src/pretrained_models/critic_best_0930.pth'
  ##NEW TAIL
  # actor_path: '/home/iff/drlenv/src/iffenv/srctail/test_newtail_offline/TD01/actor_6_5969.pth'
  # actor_path: '/home/iff/drlenv/src/iffenv/srctail/newKF_BC/1/actor_1.pth'
  actor_path: '/home/iff/drlenv/src/iffenv/srctail/newIQL_off/amq1/actor_6_5659.pth'
  # actor_path: '/home/iff/drlenv/src/iffenv/srctail/ctcl_off/1/actor_4_5369.pth'
  # actor_path: '/home/iff/drlenv/src/iffenv/srctail/newKF_offline/TDo2/actor_3_4099.pth'
  # actor_path: "/home/iff/drlenv/src/iffenv/srctail/test_newtail_offline/TD0_eff_1/actor_9_4629.pth"
  # actor_path: "/home/iff/drlenv/src/iffenv/srctail/newKF_offline_mlp/mlp1/actor_5_5389.pth"
  # actor_path: "/home/iff/drlenv/src/iffenv/srctail/newKF_AMQ/amq3/actor_2_3629.pth"
  # actor_path: "/home/iff/drlenv/src/iffenv/srctail/fy_BC/fy_BC/actor_11.pth"
  # critic_path: '/home/iff/drlenv/src/iffenv/srctail/newKF_BC/IQL_80_75_08/V_new_best_269_0.0903.pth'
  # critic_path: "/home/iff/drlenv/src/iffenv/srctail/newtail_model/IQL_15_025/V_new_best_219_0.0311.pth"
  critic_path: '/home/iff/drlenv/src/iffenv/srctail/newKF_BC/IQL_15_025new/V_new_best_262_0.0931.pth'
  # actor_path: '/home/iff/drlenv/src/iffenv/src/off2on_model_mlp2/actor_3_2869.pth'
  # critic_path: '/home/iff/drlenv/src/iffenv/src/off2on_model_mlp2/V_new_best_24_0.8371.pth'
  train_target: 1
offline:
  is_double_q: true #IQL
  sa_type: 'separate' #'separate' or 'concat'
  omega: 0.8
  target_update_freq: 2
  tau: 0.005
  offline_epoch: 1
  bc_kl: 'data'
  kl_alpha: 0.1
  mu_ratio: 1.0
  dist_ratio: 1.0
  entropy_ratio: 0.01
  offline_episodes: 160
  ope_length: 118
  offline_batch_size: 64
  offline_timesteps: 32
  offline_eval: 10
  update_type: 'optimistic' # conservative or optimistic or bet-on-Q/G
  adv_type: 'TD0' #IQL or TD0
  rollout_bias: 0 # The avg bias of the transition model
  reverse_steps: 50 #If policy can not get better for X updates, reverse it to old pi
transition:
  d_lr: 0.001
  prediction_type: 'original' #'original' f(s,a) -> s' or 'delta' f(s,a) -> s'-s
  uncertainty_mode: 'aleatoric'
  sa2s: true #if true E(s)+E(a)->s'; false E(s)->s', E is encoder
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 300
  render: false
  save_interval: 100
IFF:
  n_iff: 8
  interval: 10
  excution_time: 0.035
  steady_time: 0.0  #steady observations
  control_frequency: 20
  motor_velocity: 0.15
  refresh_time: 18
  starting_index: 0 #Default=0
  bf_directory: "Data_wzy"
  r_alpha: 1.2
  r_beta: 0.4
  r_gamma: 0.1
  mid_values: [
    180, 180, 180, 180, #left 1-4
    180, 180, 180, 180  #right 5-8 
    ]
LPFilter: #wasted
  sample_rate: 220
  cutoff_freq: 10.0
  order: 5
time_weight: 50
y_weight: 0
alpha_weight: 50
rl_train: false
save: true
seed: 'group1'
# seed: 'BF_tail_fxbest'
rl_directory: "RLtest/TPPO"
cl_list_len: 20